winzou_state_machine:
    sylius_shipment:
        callbacks:
            after:
                monsieur_biz_order_history_notify_create:
                    on: 'create'
                    do: [ '@MonsieurBiz\SyliusOrderHistoryPlugin\Notifier\OrderHistoryWithShipmentDataNotifier', 'notifyEvent' ]
                    args: [ 'object.getOrder()', 'constant("MonsieurBiz\\SyliusOrderHistoryPlugin\\Entity\\OrderHistoryEventInterface::TYPE_SHIPMENT")', '"new"' ]
                monsieur_biz_order_history_notify_cancel:
                    on: 'cancel'
                    do: [ '@MonsieurBiz\SyliusOrderHistoryPlugin\Notifier\OrderHistoryWithShipmentDataNotifier', 'notifyEvent' ]
                    args: [ 'object.getOrder()', 'constant("MonsieurBiz\\SyliusOrderHistoryPlugin\\Entity\\OrderHistoryEventInterface::TYPE_SHIPMENT")', '"cancelled"' ]
                monsieur_biz_order_history_notify_ship:
                    on: 'ship'
                    do: [ '@MonsieurBiz\SyliusOrderHistoryPlugin\Notifier\OrderHistoryWithShipmentDataNotifier', 'notifyEvent' ]
                    args: [ 'object.getOrder()', 'constant("MonsieurBiz\\SyliusOrderHistoryPlugin\\Entity\\OrderHistoryEventInterface::TYPE_SHIPMENT")', '"shipped"' ]
